// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzAGg6ru7za8FCdzUA1wOGY77srE-i0hQ',
    appId: '1:1062951577761:web:7dacf3d7b3983f7dbbe8e0',
    messagingSenderId: '1062951577761',
    projectId: 'seguridad-e296c',
    authDomain: 'seguridad-e296c.firebaseapp.com',
    storageBucket: 'seguridad-e296c.firebasestorage.app',
    measurementId: 'G-J7WJP17G57',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoavmb3hjeYKeQIYME997KvzLt4xm9P3w',
    appId: '1:1062951577761:android:513995b945c8d3a3bbe8e0',
    messagingSenderId: '1062951577761',
    projectId: 'seguridad-e296c',
    storageBucket: 'seguridad-e296c.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC42u6xEkzacF5JUn_B0dfcSV3QmMpTpLY',
    appId: '1:1062951577761:ios:e8ada8b136f35a33bbe8e0',
    messagingSenderId: '1062951577761',
    projectId: 'seguridad-e296c',
    storageBucket: 'seguridad-e296c.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC42u6xEkzacF5JUn_B0dfcSV3QmMpTpLY',
    appId: '1:1062951577761:ios:e8ada8b136f35a33bbe8e0',
    messagingSenderId: '1062951577761',
    projectId: 'seguridad-e296c',
    storageBucket: 'seguridad-e296c.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzAGg6ru7za8FCdzUA1wOGY77srE-i0hQ',
    appId: '1:1062951577761:web:9cbe35dd0d95cf1ebbe8e0',
    messagingSenderId: '1062951577761',
    projectId: 'seguridad-e296c',
    authDomain: 'seguridad-e296c.firebaseapp.com',
    storageBucket: 'seguridad-e296c.firebasestorage.app',
    measurementId: 'G-9N0VX8P38B',
  );
}
